version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  media_backups: {}
  static_backups: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: ./new.env
    ports:
      - "5433:5432"
    

  postgres_slave:
    build: ./compose/postgres
    links:
      - postgres:master
    env_file: ./new.env
   
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    # user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - media_backups:/var/pyconng
    command: /gunicorn.sh
    env_file: ./new.env

  nginx:
    build: ./compose/nginx
    depends_on:
      - django

      - certbot

    ports:
      - "0.0.0.0:80:80"

    environment:
      - MY_DOMAIN_NAME=pycon.pythonnigeria.org
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - media_backups:/var/pyconng
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d pythonnigeria.org -d *.pythonnigeria.org -d www.pythonnigeria.org --text --agree-tos --email hello@pycon.pythonnigeria.org --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm


  redis:
    image: redis:latest

